### ISSUE TITLE
A question about MRI data

### ISSUE THREAD

**Issue by sparkler0323** [roshchupkin/AllenBrainPy#1]
I just read your code about Allen gene expression, and I have a question about the data you put in MRI 

such as 'rs_reorder_T1_donor9861.nii'

Can I ask you how to make the image in MNI space ? Because the coord is not the same with the MNI cood in SampleAnnot.

Sorry for disturbing you !

**Comment by roshchupkin** [comment]
Hi! 

I used mni_icbm152_brain.nii.gz MNI template (you can find it in dropbox folder) for my own voxel-wise analysis. But the original Allen Brain T1 images are in different space and with different orientation.
So, first,  I used [elastix](http://elastix.isi.uu.nl/) to register original AB T1 to MNI template.
Then I made nifti images with samples coordinates in original AB space. 
Finally, I used "transformix" tool from elastix to apply transformation parameters (which I got from 1st step) to samples images to transform them to my MNI space. 

Does it make sense for you? 
Let me know if you have any questions.

Best,
Gena.

**Comment by sparkler0323** [comment]
Dear Gena,

Thank you very much !

I know what you means, but I'm not sure about whether it's the best way to do such things.Because we can get absolute coordinates in MNI in SampleAnnot.csv, so we can easily do the transform to any MNI space we want .

your data(first brain, first sample):
>>> np.where(Allen == 1)
(array([105, 105]), array([108, 108]), array([124, 125]))


>>> from nibabel import affine
>>> affines.apply_affine(linalg.inv(MNI.get_affine()),[5.9,-27.7,49.7])
array([ 103.9,  106.3,  121.7])

The results are very close, and I'm not sure which method is the best way.

**Comment by roshchupkin** [comment]
@sprak0323, Oh, I see your point. Yes, you are right.  But to use such affine transformation you have to be sure that the registration was done correctly and accurately enough.
Based on my experience, I prefered to do everything myself. They provide original scans and sample coordinates, so it is not so difficult to do this.

**Comment by sparkler0323** [comment]
Thank you very much, and I will do in your way.

But I might just find a bug in your code:

        >>> if samples_id is not None:
                mask=np.ones_like(range(gene_expression.shape[1]), dtype=bool)
                mask[samples_id]=False
                gene_expression_inside=gene_expression[:,mask]
                gene_expression_outside=gene_expression[:,~mask]
                gene_expression_inside_bin=gene_expression_bin[:,mask]
                gene_expression_outside_bin=gene_expression_bin[:,~mask]

I think " mask[samples_id]=False" ,the samples_id should be the index of the samples and it should be "mask[samples_id-1]=False" in python.

You may use "BIN1" gene and may report an error.

 Sorry for disturbing you

**Comment by roshchupkin** [comment]
@sprak0323 Yes, you are right! Strange, it was fixed in my local version. Anyhow, just updated the code. Thanks again.

If you find more bugs, let me know. I don't expect more, but who knows :)
